### ISSUE TITLE
Day 21 wiki page typo

### ISSUE THREAD

**Issue by mierzejk** [villuna/aoc23#1]
There is a typo at the very beginning of the following formula `let p2 = ((n+1)*(n*1)) * odd_full + (n*n) * even_full - (n+1) * odd_corners + n * even_corners;` on the [day 21 wiki page](https://github.com/villuna/aoc23/wiki/A-Geometric-solution-to-advent-of-code-2023,-day-21). The `n*1` product should be a sum `n+1`.

By the way, I spent a day on this formula and could not come up with a correct result just because I did not realize _corners_ at 4 cardinal directions could be summed up to be 4 corners of one full garden. I was adding and subtracting them independently, and apparently I must have a bug in my code. So many thanks for a visual, cohesive rundown!

**Comment by villuna** [comment]
Thank you, I've fixed it now :)
and thanks for reading, i appreciate it
